---
- name: Setup Tomcat
  hosts: all
  become: yes

  tasks:

    - name: Install Java
      yum:
        name: java-21-amazon-corretto
        state: present

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.59/bin/apache-tomcat-10.1.59.tar.gz"
        dest: "/root/apache-tomcat-10.1.59.tar.gz"
        mode: '0644'

    - name: Extract Tomcat
      unarchive:
        src: "/root/apache-tomcat-10.1.59.tar.gz"
        dest: "/root"
        remote_src: yes
        creates: "/root/apache-tomcat-10.1.59"

    - name: Rename Tomcat directory
      command: mv /root/apache-tomcat-10.1.59 /root/tomcat
      args:
        creates: /root/tomcat

    - name: Setting the roles in tomcat-users.xml
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: Configure manager context.xml
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: Create Tomcat systemd service
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          Type=forking
          User=root
          Group=root

          Environment="JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto"
          Environment="CATALINA_HOME=/root/tomcat"

          ExecStart=/root/tomcat/bin/startup.sh
          ExecStop=/root/tomcat/bin/shutdown.sh

          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes
